urs100:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      joint_urs100:
        type: position_controllers/JointPositionController
        joint: joint_urs100
        # TODO: No PID gains?